# ./roles/docker_install/tasks/create_download_folder.yml
---
- name: Create download folder
  ansible.builtin.file:
    path: "{{ dest_path }}/rpm"
    recurse: yes
    state: directory
    mode: "0755"
...